name: Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, ready_for_review]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update && \
          apt-get install -y \
          libgeos-dev
        python -m pip install --upgrade pip
        python -m pip install -e .[test]
    - name: Test with pytest
      run: |
        pytest
